version: '3.3'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - - N8N_BASIC_AUTH_PASSWORD=RahasiaBaru123!
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
    volumes:
      - ~/.n8n:/home/node/.n8n
